version: '3'

services:
  api:
    build:
      context: ./cs-insights-backend
      dockerfile: Dockerfile.development
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      MONGO_HOST: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/cs-insights-backend/node_modules"
      - "./cs-insights-backend:/cs-insights-backend"
  mongo:
    image: mongo:5.0.9
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - 27017
    command: mongod
    volumes:
      - ~/mongo/data:/data/db
  frontend:
    build:
      context: ./cs-insights-frontend
      dockerfile: Dockerfile.development
    restart: always
    env_file: .env
    command: npm start
    ports:
      - 80:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/cs-insights-frontend/node_modules"
      - "./cs-insights-frontend:/cs-insights-frontend"