version: '3'

services:
  backend:
    build:
      context: ./cs-insights-backend
      dockerfile: Dockerfile.development
    restart: always
    env_file: .env.development
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      MONGO_HOST: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      # - /cs-insights-backend/node_modules
      - ./cs-insights-backend:/cs-insights-backend
  mongo:
    image: mongo:5.0.9
    restart: always
    env_file: .env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - 27017
    command: mongod
    volumes:
      - ~/mongo/data:/data/db
    logging:
      driver: "none"
  frontend:
    build:
      context: ./cs-insights-frontend
      dockerfile: Dockerfile.development
    restart: always
    env_file: .env.development
    command: npm start
    ports:
      - 3001:3001
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "/cs-insights-frontend/node_modules"
      - "./cs-insights-frontend:/cs-insights-frontend"
  prediction-endpoint:
    build:
      context: ./cs-insights-prediction-endpoint
      dockerfile: Dockerfile.development
    restart: always
    env_file: .env.development
    command: bash -c "poetry install && poetry run python -m dev" # Poetry install here because the mounted volumes are necessary for installing the project as a package
    ports:
      - 8000:8000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./cs-insights-prediction-endpoint:/cs-insights-prediction-endpoint
