version: "3.1"

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  backend:
    build: ./cs-insights-backend
    # image: ghcr.io/jpwahle/cs-insights-backend:latest
    depends_on:
      - mongo
    restart: always
    env_file: .env
    command: npm run cluster
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: ${MONGO_HOST}
    secrets:
      - mongo_user
      - mongo_password
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  mongo:
    image: mongo:5.0.9
    restart: always
    env_file: .env
    expose:
      - 27017
    command: mongod
    volumes:
      - ~/mongo/data:/data/db
  frontend:
    build: ./cs-insights-frontend
    # image: ghcr.io/jpwahle/cs-insights-frontend:latest
    command: nginx -g "daemon off;"
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file: .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /etc/letsencrypt/live/cs-insights/privkey.pem:/etc/letsencrypt/live/cs-insights/privkey.pem
      - /etc/letsencrypt/live/cs-insights/fullchain.pem:/etc/letsencrypt/live/cs-insights/fullchain.pem
  prediction-endpoint:
    build: ./cs-insights-prediction-endpoint
    # image: ghcr.io/jpwahle/cs-insights-prediction-endpoint:latest
    restart: always
    env_file: .env
    command: poetry run python -m prod --workers 2
    secrets:
      - mongo_user
      - mongo_password
      - jwt_secret
    expose:
      - 8000
    ports:
      - 8000:8000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ~/prediction-endpoint/saved_models:/cs-insights-prediction-endpoint/saved_models
secrets:
  mongo_user:
    file: mongo_user.txt
  mongo_password:
    file: mongo_password.txt
  jwt_secret:
    file: jwt_secret.txt
