name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: cs-insights-main
      - uses: actions/checkout@v2
        with:
          repository: gipplab/cs-insights-main.github.io
          path: ./cs-insights-main.github.io
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-redirects
          pip install mkdocs-material
          mkdocs gh-deploy --config-file ../cs-insights-main/mkdocs.yml --force
        working-directory: ./cs-insights-main.github.io
