name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-redirects
          pip install mkdocs-material
          mkdocs gh-deploy --config-file ../cs-insights-main/mkdocs.yml --force
        working-directory: ./cs-insights-main.github.io
